language: python
cache: pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
dist: trusty
sudo: false
install:
  - make deps
  - make deps-test
script:
  - coverage run --source=yarg runtests.py
after_success:
  - coveralls
  - curl -X POST https://readthedocs.org/build/yarg
